<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ticket extends \AppBundle\Entity\Ticket implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'libelle', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'etat', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'datecrea', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'echeance', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'idproj', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'iddev'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'libelle', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'etat', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'datecrea', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'echeance', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'idproj', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'iddev'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ticket $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecrea($datecrea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecrea', [$datecrea]);

        return parent::setDatecrea($datecrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecrea', []);

        return parent::getDatecrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcheance($echeance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcheance', [$echeance]);

        return parent::setEcheance($echeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcheance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcheance', []);

        return parent::getEcheance();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdproj(\AppBundle\Entity\Projet $idproj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdproj', [$idproj]);

        return parent::setIdproj($idproj);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdproj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproj', []);

        return parent::getIdproj();
    }

    /**
     * {@inheritDoc}
     */
    public function addIddev(\AppBundle\Entity\Developpeur $iddev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIddev', [$iddev]);

        return parent::addIddev($iddev);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIddev(\AppBundle\Entity\Developpeur $iddev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIddev', [$iddev]);

        return parent::removeIddev($iddev);
    }

    /**
     * {@inheritDoc}
     */
    public function getIddev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddev', []);

        return parent::getIddev();
    }

}
